// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using labclothingcollection.Context;

#nullable disable

namespace labclothingcollection.Migrations
{
    [DbContext(typeof(LabClothingCollectionContext))]
    [Migration("20230623005744_seeds")]
    partial class seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("labclothingcollection.Models.Colecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnoLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estacao")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orcamento")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdentificador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("UsuarioIdentificador");

                    b.ToTable("Colecao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = new DateTime(1991, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estacao = 2,
                            Marca = "Marca 1",
                            Nome = "Nome 1",
                            Orcamento = 1000,
                            Status = 0,
                            UsuarioIdentificador = 1
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = new DateTime(1991, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estacao = 3,
                            Marca = "Marca 2",
                            Nome = "Nome 2",
                            Orcamento = 1500,
                            Status = 0,
                            UsuarioIdentificador = 2
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = new DateTime(1993, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estacao = 0,
                            Marca = "Marca 3",
                            Nome = "Nome 3",
                            Orcamento = 2000,
                            Status = 1,
                            UsuarioIdentificador = 1
                        },
                        new
                        {
                            Id = 4,
                            AnoLancamento = new DateTime(1985, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estacao = 1,
                            Marca = "Marca 4",
                            Nome = "Nome 4",
                            Orcamento = 100,
                            Status = 0,
                            UsuarioIdentificador = 1
                        },
                        new
                        {
                            Id = 5,
                            AnoLancamento = new DateTime(1970, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estacao = 0,
                            Marca = "Marca 5",
                            Nome = "Nome 5",
                            Orcamento = 3500,
                            Status = 1,
                            UsuarioIdentificador = 2
                        });
                });

            modelBuilder.Entity("labclothingcollection.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColecaoId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColecaoId = 1,
                            Layout = 0,
                            Nome = "Nome 1",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 2,
                            ColecaoId = 2,
                            Layout = 2,
                            Nome = "Nome 2",
                            Tipo = 4
                        },
                        new
                        {
                            Id = 3,
                            ColecaoId = 1,
                            Layout = 1,
                            Nome = "Nome 3",
                            Tipo = 6
                        },
                        new
                        {
                            Id = 4,
                            ColecaoId = 1,
                            Layout = 0,
                            Nome = "Nome 4",
                            Tipo = 5
                        },
                        new
                        {
                            Id = 5,
                            ColecaoId = 1,
                            Layout = 2,
                            Nome = "Nome 5",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 6,
                            ColecaoId = 2,
                            Layout = 1,
                            Nome = "Nome 6",
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("labclothingcollection.Models.Usuario", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Identificador");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Identificador = 1,
                            Cpf = "123.456.789-00",
                            DataNascimento = new DateTime(1991, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "teste@teste.com",
                            Genero = "masculino",
                            Nome = "Lucas Silva",
                            Status = 0,
                            Telefone = "9512328",
                            Tipo = 2
                        },
                        new
                        {
                            Identificador = 2,
                            Cpf = "987.654.321-00",
                            DataNascimento = new DateTime(1930, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "teste2@example.com",
                            Genero = "feminino",
                            Nome = "Camila Z",
                            Status = 1,
                            Telefone = "987654321",
                            Tipo = 0
                        },
                        new
                        {
                            Identificador = 3,
                            Cpf = "456.789.123-00",
                            DataNascimento = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "teste3@dominio.com",
                            Genero = "feminino",
                            Nome = "Maria das Dores",
                            Status = 1,
                            Telefone = "456789123",
                            Tipo = 1
                        },
                        new
                        {
                            Identificador = 4,
                            Cpf = "789.123.456-00",
                            DataNascimento = new DateTime(1987, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "teste4@example.com",
                            Genero = "feminino",
                            Nome = "Ana Rodrigues",
                            Status = 0,
                            Telefone = "321654987",
                            Tipo = 3
                        },
                        new
                        {
                            Identificador = 5,
                            Cpf = "321.654.987-00",
                            DataNascimento = new DateTime(1982, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "teste5@example.com",
                            Genero = "Masculino",
                            Nome = "Luiz Ferreira",
                            Status = 0,
                            Telefone = "321654987",
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("labclothingcollection.Models.Colecao", b =>
                {
                    b.HasOne("labclothingcollection.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdentificador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("labclothingcollection.Models.Modelo", b =>
                {
                    b.HasOne("labclothingcollection.Models.Colecao", "Colecao")
                        .WithMany()
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");
                });
#pragma warning restore 612, 618
        }
    }
}
